//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nlbdataEntities1 : DbContext
    {
        public nlbdataEntities1()
            : base("name=nlbdataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Choice> Choices { get; set; }
        public virtual DbSet<NBA_ADMIN> NBA_ADMIN { get; set; }
        public virtual DbSet<NBA_Audit_trail> NBA_Audit_trail { get; set; }
        public virtual DbSet<NBA_Core> NBA_Core { get; set; }
        public virtual DbSet<NBA_Documents> NBA_Documents { get; set; }
        public virtual DbSet<NBA_Entry_Points> NBA_Entry_Points { get; set; }
        public virtual DbSet<NBA_Gender> NBA_Gender { get; set; }
        public virtual DbSet<NBA_Grade> NBA_Grade { get; set; }
        public virtual DbSet<NBA_HighSchoolQuizz> NBA_HighSchoolQuizz { get; set; }
        public virtual DbSet<NBA_Identification> NBA_Identification { get; set; }
        public virtual DbSet<NBA_MessageID> NBA_MessageID { get; set; }
        public virtual DbSet<NBA_Occupation> NBA_Occupation { get; set; }
        public virtual DbSet<NBA_Period_Maintenance> NBA_Period_Maintenance { get; set; }
        public virtual DbSet<NBA_PR> NBA_PR { get; set; }
        public virtual DbSet<NBA_RiskAssessment> NBA_RiskAssessment { get; set; }
        public virtual DbSet<NBA_Role> NBA_Role { get; set; }
        public virtual DbSet<NBA_SemesterMaintenance> NBA_SemesterMaintenance { get; set; }
        public virtual DbSet<NBA_ServicePlan> NBA_ServicePlan { get; set; }
        public virtual DbSet<NBA_ServicePlanIntervention> NBA_ServicePlanIntervention { get; set; }
        public virtual DbSet<NBA_Status> NBA_Status { get; set; }
        public virtual DbSet<NBA_SYS_Users> NBA_SYS_Users { get; set; }
        public virtual DbSet<NBA_TaskDiary> NBA_TaskDiary { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<RiskAssessment_view> RiskAssessment_view { get; set; }
        public virtual DbSet<NBA_Agwy> NBA_Agwy { get; set; }
    }
}
