//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBA_ServicePlan
    {
        public int SERVICEPLAN_ID { get; set; }
        public string service_plan_description { get; set; }
        public Nullable<int> DOCUMENT_ID { get; set; }
        public Nullable<int> AGWY_ID { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public Nullable<int> SYS_USERS_ID { get; set; }
        public Nullable<int> SEMESTER_ID { get; set; }
        public Nullable<int> RISK_ID { get; set; }
        public Nullable<int> CORE_ID { get; set; }
    }
}
