//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBA_Audit_trail
    {
        public int CHANGE_ID { get; set; }
        public string tablename { get; set; }
        public string fieldname { get; set; }
        public Nullable<int> record_id { get; set; }
        public string oldvalue { get; set; }
        public string newvalue { get; set; }
        public Nullable<System.DateTime> changedate { get; set; }
        public string changeby { get; set; }
        public Nullable<int> SYS_USER_ID { get; set; }
    }
}
