//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NBA_Agwy
    {
        public int AGWY_ID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string known_as { get; set; }
        public Nullable<int> gender { get; set; }
        public string age { get; set; }
        public Nullable<int> type_of_identification { get; set; }
        public string idno { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dateOfbirth { get; set; }
        public string maiden_name { get; set; }
        public string house_number { get; set; }
        public string street_name { get; set; }
        public string town_village_address { get; set; }
        public string town_village { get; set; }
        public string uic { get; set; }
        public string email { get; set; }
        public Nullable<int> phone_number { get; set; }
        public Nullable<int> alternative_number { get; set; }
        public string alternative_number_relationship { get; set; }
        public string attended_school { get; set; }
        public string name_of_school { get; set; }
        public string grade { get; set; }
        public Nullable<int> higest_grade_passed { get; set; }
        public string currrent_occupation { get; set; }
        public string approval_flag { get; set; }
        public string concent_flag { get; set; }
        public byte[] mimetype { get; set; }
        public byte[] imagedata { get; set; }
        public string describe_living { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string status { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> SEMESTER_ID { get; set; }
        public Nullable<int> SYS_USER_ID { get; set; }
        public Nullable<int> DOCUMENT_ID { get; set; }
        public Nullable<int> Core_ID { get; set; }
        public Nullable<int> messageInquiry { get; set; }
        public Nullable<int> EntryPoint_ID { get; set; }
        public Nullable<int> HighSchoolQuizz_ID { get; set; }
        public Nullable<int> RISK_ID { get; set; }
    
        public virtual NBA_MessageID NBA_MessageID { get; set; }
        public virtual NBA_Core NBA_Core { get; set; }
        public virtual NBA_Documents NBA_Documents { get; set; }
        public virtual NBA_Entry_Points NBA_Entry_Points { get; set; }
        public virtual NBA_Gender NBA_Gender { get; set; }
        public virtual NBA_Grade NBA_Grade { get; set; }
        public virtual NBA_HighSchoolQuizz NBA_HighSchoolQuizz { get; set; }
        public virtual NBA_Identification NBA_Identification { get; set; }
        public virtual NBA_Occupation NBA_Occupation { get; set; }
        public virtual NBA_SYS_Users NBA_SYS_Users { get; set; }
    }
}
