//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBA_ADMIN
    {
        public int ADMIN_ID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public int IsEmailVerified { get; set; }
        public System.Guid VerificationCode { get; set; }
        public int ROLE_ID { get; set; }
        public Nullable<int> SYSUSER_ID { get; set; }
    }
}
