//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBA_Core
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NBA_Core()
        {
            this.NBA_Agwy = new HashSet<NBA_Agwy>();
        }
    
        public int CORE_ID { get; set; }
        public string description { get; set; }
        public string TB_assess { get; set; }
        public string HIV_assess { get; set; }
        public string Condom_educate { get; set; }
        public string STI_assess { get; set; }
        public Nullable<int> RISK_ID { get; set; }
        public Nullable<int> AGWY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NBA_Agwy> NBA_Agwy { get; set; }
    }
}
