//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAssessment_view
    {
        public int CATEGORY_ID { get; set; }
        public string category { get; set; }
        public int QUESTION_ID { get; set; }
        public string questions { get; set; }
        public string status { get; set; }
        public int ANSWER_TYPE_ID { get; set; }
        public string Expr1 { get; set; }
    }
}
