//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBA_ServicePlanIntervention
    {
        public int INTERVENTION_ID { get; set; }
        public string type { get; set; }
        public string service_ui { get; set; }
        public Nullable<System.DateTime> service_delivery_date { get; set; }
        public Nullable<System.DateTime> semester_end_date { get; set; }
        public string status { get; set; }
        public Nullable<int> SEMESTER_ID { get; set; }
        public Nullable<int> SYS_USER_ID { get; set; }
    }
}
