//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBA_Documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NBA_Documents()
        {
            this.NBA_Agwy = new HashSet<NBA_Agwy>();
        }
    
        public int DOCUMENT_ID { get; set; }
        public string doc_name { get; set; }
        public string description { get; set; }
        public string classification { get; set; }
        public Nullable<System.DateTime> doc_date { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NBA_Agwy> NBA_Agwy { get; set; }
    }
}
