//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NBA_Agwy
    {
        public int AGWY_ID { get; set; }

        [Display(Name = "First Name")]

        [Required(AllowEmptyStrings = false, ErrorMessage = "First name required")]
        public string name { get; set; }

        [Display(Name = "Second Name")]

        [Required(AllowEmptyStrings = false, ErrorMessage = "Second required")]
        public string surname { get; set; }
        [Display(Name = "Known -As")]

        [Required(AllowEmptyStrings = false, ErrorMessage = "Second name required")]
        public string known_as { get; set; }
        [Display(Name = "Gender")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Gender required")]
        public Nullable<int> gender { get; set; }

        [Display(Name = "Age")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Age required")]
        public string age { get; set; }
        [Display(Name = "Type of Identification")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Identification type required")]
        public Nullable<int> type_of_identification { get; set; }

        [Display(Name = "ID number")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "ID number required") ]
        public string idno { get; set; }

        [Display(Name = "Date of Birth")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Date of Birth required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        //[DataType(DataType.Date)]
        public Nullable<System.DateTime> dateOfbirth { get; set; }

        [Display(Name = "Mothers Maiden Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Mother Maiden required")]

        public string maiden_name { get; set; }

        [Display(Name = "House number")]
        public string house_number { get; set; }

        [Display(Name ="Street name")]
        public string street_name { get; set; }
        [Display(Name = "Town or Village ")]
        public string town_village_address { get; set; }

        [Display(Name = "Town or Village birth")]
        public string town_village { get; set; }

        [Display(Name = "UIC")]
        public string uic { get; set; }

        [Display(Name = "Email")]
        public string email { get; set; }
        [Display(Name = "Phone Number")]
        public Nullable<int> phone_number { get; set; }

        [Display(Name = "Alternative number")]
        public Nullable<int> alternative_number { get; set; }

        [Display(Name = "Relation with Alternative Number")]
        public string alternative_number_relationship { get; set; }



        [Display(Name = "Attended School")]

        public string attended_school { get; set; }
        [Display(Name = "Name of School")]
        public string name_of_school { get; set; }

        [Display(Name = "Grade")]
        public string grade { get; set; }


        [Display(Name ="Highest grade passed")]
        public Nullable<int> higest_grade_passed { get; set; }

        [Display(Name = "What you doing")]
        public string currrent_occupation { get; set; }
        public string approval_flag { get; set; }
        public string concent_flag { get; set; }
        public byte[] mimetype { get; set; }
        public byte[] imagedata { get; set; }

        [Display(Name = "Describe living")]
        public string describe_living { get; set; }
        [Display(Name = "Registration date")]
        public Nullable<System.DateTime> reg_date { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string status { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> SEMESTER_ID { get; set; }

        [Display(Name = "System User ID")]
        public Nullable<int> SYS_USER_ID { get; set; }
        public Nullable<int> DOCUMENT_ID { get; set; }
        public Nullable<int> Core_ID { get; set; }

        [Display(Name = "Message Inquiry")]
        public Nullable<int> messageInquiry { get; set; }
        [Display(Name = "Entry Point")]
        public Nullable<int> EntryPoint_ID { get; set; }

        [Display(Name = "Did you attend school")]
        public Nullable<int> HighSchoolQuizz_ID { get; set; }
        public Nullable<int> RISK_ID { get; set; }
    
        public virtual NBA_MessageID NBA_MessageID { get; set; }
        public virtual NBA_Core NBA_Core { get; set; }
        public virtual NBA_Documents NBA_Documents { get; set; }
        public virtual NBA_Entry_Points NBA_Entry_Points { get; set; }
        public virtual NBA_Gender NBA_Gender { get; set; }
        public virtual NBA_Grade NBA_Grade { get; set; }
        public virtual NBA_HighSchoolQuizz NBA_HighSchoolQuizz { get; set; }
        public virtual NBA_Identification NBA_Identification { get; set; }
        public virtual NBA_Occupation NBA_Occupation { get; set; }
        public virtual NBA_SYS_Users NBA_SYS_Users { get; set; }
    }
}
