//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBA_PR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NBA_PR()
        {
            this.NBA_Entry_Points = new HashSet<NBA_Entry_Points>();
            this.NBA_SYS_Users = new HashSet<NBA_SYS_Users>();
        }
    
        public int ID { get; set; }
        public string PR_SR_ID { get; set; }
        public string PR_name { get; set; }
        public string SR_name { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string subdistrict { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NBA_Entry_Points> NBA_Entry_Points { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NBA_SYS_Users> NBA_SYS_Users { get; set; }
    }
}
