//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBA_Period_Maintenance
    {
        public int Period_ID { get; set; }
        public string period_name { get; set; }
        public Nullable<System.DateTime> period_start_date { get; set; }
        public Nullable<System.DateTime> period_end_date { get; set; }
        public string status { get; set; }
        public int SERVICEPLAN_ID { get; set; }
    
        public virtual NBA_Period_Maintenance NBA_Period_Maintenance1 { get; set; }
        public virtual NBA_Period_Maintenance NBA_Period_Maintenance2 { get; set; }
    }
}
