//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacsolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBA_SYS_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NBA_SYS_Users()
        {
            this.NBA_Agwy = new HashSet<NBA_Agwy>();
        }
    
        public int SYS_USER_ID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> mobile { get; set; }
        public string employee_id { get; set; }
        public string organization { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string subdistrict { get; set; }
        public string image { get; set; }
        public string SR_name { get; set; }
        public Nullable<int> Entry_ID { get; set; }
        public string email { get; set; }
        public bool sys_IsEmailVerified { get; set; }
        public Nullable<System.Guid> sys_VerificationCode { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<int> ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NBA_Agwy> NBA_Agwy { get; set; }
        public virtual NBA_PR NBA_PR { get; set; }
        public virtual NBA_Role NBA_Role { get; set; }
    }
}
